# zenn-backend/docker-compose.yml
version: "3.8"

services:
  e2e:
    container_name: e2e
    image: "cypress/included:4.1.0"
    # "cypress/included" images have entrypoint set to globally installed cypress
    # so the command can simply add any arguments
    command: "run --browser chrome"
    working_dir: /e2e
    volumes:
      - .:/e2e
    network_mode: "host"
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
